#!/bin/bash
echo "apk address:"
read var  
adb devices > tmp.txt
while read line
do
dev_id=`echo $line|awk '{print $1}'`
if [ -z $dev_id ]
then 
break
fi
if [ $dev_id = List ]
then
continue
fi
adb -s $dev_id install -r $var
done < tmp.txt
rm tmp.txt
